version: '3.8'
services:
  movingworld:
    build: 
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ../:/app:cached
    network_mode: service:db
    command: sleep infinity

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: movingworld
      POSTGRES_USER: movingworld
      POSTGRES_DB: movingworld
    ports:
      - 5432:5432

volumes:
  postgres-data: